services:
  # Auth Service
  auth-service:
    container_name: auth-service
    build:
      context: ./app/auth-service
      dockerfile: Dockerfile.simple
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=challenge_db
      - JWT_SECRET=jwt-secret-key-change-in-production
      - JWT_REFRESH_SECRET=jwt-refresh-secret-key-change-in-production
      - JWT_ACCESS_EXPIRE=15m
      - JWT_REFRESH_EXPIRE=7d
    depends_on:
      - db
    networks:
      - challenge-network

  # Postgres Database
  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    ports:
      - '5432:5432'
    networks:
      - challenge-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge_db

volumes:
  postgres_data:
    driver: local

networks:
  challenge-network:
    driver: bridge